<?php

/**
 * Implements hook_form_alter().
 */
function kt2015_menu_form_alter(&$form, &$form_state, $form_id) {
	if($form_id == 'block_admin_configure' && $form['delta']['#value'] == 'main-menu'){
		$form['kt2015_mm_image_fid'] = array(
			'#type' => 'managed_file',
			'#title' => t('Main Menu Image'),
			'#default_value' => variable_get('kt2015_mm_image_fid', ''),
			'#upload_location' => 'public://',
		);

		$form['#submit'][] = 'kt2015_menu_form_submit';
	}
}

function kt2015_menu_form_submit($form, &$form_state){
	if(empty($form_state['values']['kt2015_mm_image_fid']) && variable_get('kt2015_mm_image_fid', '')){
		$file = file_load(variable_get('kt2015_mm_image_fid', ''));
		file_delete($file, TRUE);

		variable_set('kt2015_mm_image_fid', '');
	}
	else if(!empty($form_state['values']['kt2015_mm_image_fid'])){
		$file = file_load($form_state['values']['kt2015_mm_image_fid']);
		$file->status = FILE_STATUS_PERMANENT;
		$file->replace = FILE_EXISTS_REPLACE;
		file_save($file);
		file_usage_add($file, 'node', 'homepage', 1);

		variable_set('kt2015_mm_image_fid', $form_state['values']['kt2015_mm_image_fid']);
	}
}

/**
 * Implements hook_block_view_alter().
 */
function kt2015_menu_block_view_alter(&$data, $block) {
	if($block->delta == 'main-menu'){
		$data['content']['image'] = kt2015_menu_get_image_render_array();
	}
}

function kt2015_menu_get_image_render_array($style = 'main_menu_image'){
	$render = array();

	$image_fid = variable_get('kt2015_mm_image_fid', '');
	if($image_fid){
		$image = file_load($image_fid);

		$render = array(
			'#theme' => 'image_style',
			'#style_name' => $style,
			'#path' => $image->uri,
		);
	}

	return $render;
}